# Generated by Django 3.0.8 on 2020-08-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0004_auto_20200729_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('mm_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numberOfRounds', models.IntegerField()),
                ('currentRoundNumber', models.IntegerField()),
                ('TakeCurrentRoundInAccount', models.BooleanField()),
                ('SeriesIsOpen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('color', models.CharField(max_length=5)),
                ('handicap', models.IntegerField()),
                ('win', models.CharField(max_length=4)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_results', to='wgocra.Participant')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='wgocra.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wgocra.Series'),
        ),
    ]
