# Generated by Django 3.0.8 on 2020-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0007_auto_20200810_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='egd_pin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
