# Generated by Django 3.0.8 on 2020-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0008_auto_20200812_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
