# Generated by Django 3.0.8 on 2020-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0009_series_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='color',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='handicap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='win',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
