# Generated by Django 3.0.8 on 2020-08-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0010_auto_20200814_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_results', to='wgocra.Participant'),
        ),
    ]
