# Generated by Django 3.0.8 on 2020-08-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0012_result_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='new_rank',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='resultrating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='gain',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='r_string',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
