# Generated by Django 3.0.8 on 2020-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0013_auto_20200822_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='r_string',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
