# Generated by Django 3.0.8 on 2020-08-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0014_auto_20200822_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='gain',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
