# Generated by Django 3.0.8 on 2020-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0015_auto_20200822_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gain',
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
