# Generated by Django 3.0.8 on 2020-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0016_participant_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='games',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='wins',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
