# Generated by Django 3.0.8 on 2020-08-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0017_auto_20200822_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='score',
            new_name='points_str',
        ),
    ]
