# Generated by Django 3.0.8 on 2020-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0018_auto_20200825_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
