# Generated by Django 3.0.8 on 2020-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0023_auto_20200901_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='admin_for',
            field=models.ManyToManyField(blank=True, related_name='admin', to='wgocra.Club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(blank=True, to='wgocra.Club'),
        ),
    ]
