# Generated by Django 3.0.8 on 2020-09-02 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wgocra', '0025_series_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='admin_for',
        ),
        migrations.AddField(
            model_name='club',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admin_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
