# Generated by Django 3.0.8 on 2020-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0026_auto_20200902_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='mm_id',
            field=models.IntegerField(null=True),
        ),
    ]
