# Generated by Django 3.0.8 on 2021-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0027_auto_20200904_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='diffCutoff',
            field=models.IntegerField(default=1),
        ),
    ]
