# Generated by Django 3.0.8 on 2021-05-16 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0028_series_diffcutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='lastOpponents',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='series',
            name='startDate',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
    ]
