# Generated by Django 3.0.8 on 2021-07-22 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0029_auto_20210516_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='game',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
