# Generated by Django 3.0.8 on 2021-07-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0031_result_opponent_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='opponent_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_result', to='wgocra.Result'),
        ),
    ]
