# Generated by Django 3.0.8 on 2021-08-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0033_participant_playing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wgocra.Club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wgocra.Player')),
            ],
        ),
    ]
