# Generated by Django 3.0.8 on 2021-08-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgocra', '0034_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='club',
        ),
        migrations.AddField(
            model_name='player',
            name='last_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wgocra.Club'),
        ),
        migrations.AddField(
            model_name='rating',
            name='old_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wgocra.Series'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(blank=True, related_name='players', to='wgocra.Club'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
